language: c
os: linux
dist: bionic

addons:
  apt:
    packages:
    - pkg-config gfortran openmpi-bin libopenmpi-dev


env:
  - export FC = mpif90
  - export FC = gfortran

script:
  - $FC valentine.f90 -o be-mine.x
  - ./be-mine.x
