language: c
os: linux
dist: bionic

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - pkg-config gfortran openmpi-bin libopenmpi-dev

env:
  - FC=mpif90
  - FC=gfortran

script:
  - ${FC} valentine.f90 -o be-mine.x
  - ./be-mine.x << EOF 
  - 0.1 
  -EOF

